name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./reserve/pom.xml
          mvn clean package -f ./바운디드컨텍스트 최소4개이상하기/pom.xml
          mvn clean package -f ./BoundedContext445/pom.xml
          mvn clean package -f ./BoundedContext861/pom.xml

      - name: Docker Build and push for Reserve
        uses: docker/build-push-action@v4
        with:
          context: ./reserve
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reserve:latest
            ghcr.io/${{ github.repository }}/reserve:${{ github.ref_name }}
            
      - name: Docker Build and push for 바운디드컨텍스트최소4개이상하기
        uses: docker/build-push-action@v4
        with:
          context: ./바운디드컨텍스트 최소4개이상하기
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/바운디드컨텍스트-최소4개이상하기:latest
            ghcr.io/${{ github.repository }}/바운디드컨텍스트-최소4개이상하기:${{ github.ref_name }}
            
      - name: Docker Build and push for BoundedContext445
        uses: docker/build-push-action@v4
        with:
          context: ./BoundedContext445
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/boundedcontext445:latest
            ghcr.io/${{ github.repository }}/boundedcontext445:${{ github.ref_name }}
            
      - name: Docker Build and push for BoundedContext861
        uses: docker/build-push-action@v4
        with:
          context: ./BoundedContext861
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/boundedcontext861:latest
            ghcr.io/${{ github.repository }}/boundedcontext861:${{ github.ref_name }}
            
