name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./order/pom.xml
          mvn clean package -f ./install/pom.xml
          mvn clean package -f ./payment/pom.xml
          mvn clean package -f ./airobot/pom.xml
          mvn clean package -f ./workerSystem/pom.xml

      - name: Docker Build and push for Order
        uses: docker/build-push-action@v4
        with:
          context: ./order
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/order:latest
            ghcr.io/${{ github.repository }}/order:${{ github.ref_name }}
            
      - name: Docker Build and push for Install
        uses: docker/build-push-action@v4
        with:
          context: ./install
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/install:latest
            ghcr.io/${{ github.repository }}/install:${{ github.ref_name }}
            
      - name: Docker Build and push for Payment
        uses: docker/build-push-action@v4
        with:
          context: ./payment
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/payment:latest
            ghcr.io/${{ github.repository }}/payment:${{ github.ref_name }}
            
      - name: Docker Build and push for Airobot
        uses: docker/build-push-action@v4
        with:
          context: ./airobot
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/airobot:latest
            ghcr.io/${{ github.repository }}/airobot:${{ github.ref_name }}
            
      - name: Docker Build and push for WorkerSystem
        uses: docker/build-push-action@v4
        with:
          context: ./workerSystem
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/workersystem:latest
            ghcr.io/${{ github.repository }}/workersystem:${{ github.ref_name }}
            
