apiVersion: apps/v1
kind: Deployment
metadata:
  name: install
  namespace : airobotrental
  labels:
    app: install
spec:
  replicas: 1
  selector:
    matchLabels:
      app: install
  template:
    metadata:
      labels:
        app: install
    spec:
      containers:
        - name: install
          image: seojaeho/install:lastst
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"            
          readinessProbe: #셀프 힐링
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe: #무정지 배포
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
      volumes:  # 볼륨 추가
        - name: ebs-volume
          persistentVolumeClaim:
            claimName: ebs-pvc